server:
    port: 22111
    servlet:
        context-path: /report-mange-system
spring:
    datasource:
        url: jdbc:mysql://42.193.121.136:13306/report-mange-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: liubowen
        driver-class-name: com.mysql.cj.jdbc.Driver

        # Druid 配置
        druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            test-on-borrow: true
            test-while-idle: true
            validation-query: SELECT 1
            filters: stat,wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000