mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    use-column-label: true
    map-underscore-to-camel-case: true

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      load-on-startup: 1
  application:
    name: cmc-general-operate

  profiles:
    active: druid

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countSql

sa-token:
  #token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86,400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


com:
  linshan:
    snowflake:
        machine-id: 1
        data-center-id: 1