mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    use-column-label: true
    map-underscore-to-camel-case: true

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      load-on-startup: 1
  application:
    name: cmc-general-operate


  profiles:
    active: druid

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countSql